// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://noxdsmplywvhcdbqkxds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5veGRzbXBseXd2aGNkYnFreGRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MjYzODksImV4cCI6MjA2MDEwMjM4OX0.2h_x6o7RDQ6AhO1Qu2AWzSiHmPOl72pPXtIca94_wp4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);